# Generated by Django 3.2.9 on 2022-07-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecomplited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecomplited',
            new_name='datecompleted',
        ),
    ]
